# Generated by Django 5.0.6 on 2025-11-23 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_sent', models.BooleanField(db_index=True, default=True)),
                ('target_role', models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('administrator', 'Administrator')], max_length=20, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_broadcasts', to='core.course')),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(db_index=True, default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_delivered', models.BooleanField(db_index=True, default=True, help_text='False for scheduled messages not yet released (if you implement a scheduler).')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_sender_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_recipient_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='core.course')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direct Message',
                'verbose_name_plural': 'Direct Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_broadcast_receipts', to=settings.AUTH_USER_MODEL)),
                ('direct_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_links', to='messaging.directmessage')),
            ],
            options={
                'verbose_name': 'Broadcast Recipient',
                'verbose_name_plural': 'Broadcast Recipients',
            },
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['scheduled_for', 'is_sent'], name='messaging_b_schedul_588b11_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['target_course', 'target_role'], name='messaging_b_target__f29578_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender', 'recipient', 'created_at'], name='messaging_d_sender__cf9d78_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='messaging_d_recipie_2ba6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['is_scheduled', 'is_delivered', 'scheduled_for'], name='messaging_d_is_sche_93cf3f_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['broadcast', 'user'], name='messaging_b_broadca_5f8ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['user', 'delivered_at'], name='messaging_b_user_id_4694d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastrecipient',
            unique_together={('broadcast', 'user')},
        ),
    ]
