# Generated by Django 5.2.8 on 2025-12-09 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_satisfaction', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Satisfaction with group work (1-5)')),
                ('own_contribution', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating of own contribution (1-5)')),
                ('assignment_opinion', models.TextField(blank=True, help_text='Brief opinion on the assignment (optional)')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations (optional)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Group Questionnaire',
                'verbose_name_plural': 'Group Questionnaires',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_group_assignment',
            field=models.BooleanField(default=False, help_text='If True, this is a group assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Student who actually submitted the files', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name or identifier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.assignment')),
                ('created_by', models.ForeignKey(help_text='Teacher who created the group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(help_text='Students in this group', related_name='assignment_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment Group',
                'verbose_name_plural': 'Assignment Groups',
                'ordering': ['assignment', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group this submission belongs to (if group assignment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.assignmentgroup'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['group', 'submitted_at'], name='core_assign_group_i_1ff440_idx'),
        ),
        migrations.AddField(
            model_name='groupquestionnaire',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='core.assignmentgroup'),
        ),
        migrations.AddField(
            model_name='groupquestionnaire',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_questionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignmentgroup',
            index=models.Index(fields=['assignment', 'created_at'], name='core_assign_assignm_2dd8a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentgroup',
            unique_together={('assignment', 'name')},
        ),
        migrations.AddIndex(
            model_name='groupquestionnaire',
            index=models.Index(fields=['group', 'student'], name='core_groupq_group_i_77b279_idx'),
        ),
        migrations.AddIndex(
            model_name='groupquestionnaire',
            index=models.Index(fields=['group', 'submitted_at'], name='core_groupq_group_i_d0c5a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupquestionnaire',
            unique_together={('group', 'student')},
        ),
    ]
