# Generated by Django 5.2.8 on 2025-12-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_groupquestionnaire_assignment_is_group_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, assignment is closed and students cannot submit'),
        ),
    ]
